# .github/workflows/release.yml
name: Release

on:
  push:
    branches:
      - main  # Run this workflow when PRs are merged into 'main' branch

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # Use the version compatible with your project

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Run the release command
      - name: Run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub token for pushing release commits and tags
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}  # Add NPM_TOKEN in your GitHub secrets for authentication
        run: npm run release

      # Step 5 (Optional): Push new version to npm registry
      - name: Publish to npm
        if: success()
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}  # Add NPM_TOKEN in your GitHub secrets for authentication
        run: npm publish
